env:
  es6: true
  node: true

extends: 'eslint:recommended'

parserOptions:
  sourceType: module

rules:
  indent: [warn, tab]
  linebreak-style: [warn, unix]
  quotes: [warn, single]
  semi: [warn, never]
  no-console: 0
  no-cond-assign: 0
